[build-system]
requires = ["setuptools>=42", "setuptools_scm[toml]>=6.0", "pybind11"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "dirty-tag"
write_to = 'pyR2D2/_version.py'